### ISSUE TITLE
create anchors in All Tools

### ISSUE THREAD

**Issue by raybellwaves** [pyviz/pyviz.org#104]
https://pyviz.org/tools.html e.g. create an anchor for Geospatial to make it easier to share

**Comment by jbednar** [comment]
The anchors are there already; e.g. https://pyviz.org/tools.html#geospatial and https://pyviz.org/tools.html#native-gui . Are you wanting them to be more visible?

**Comment by raybellwaves** [comment]
> Are you wanting them to be more visible?

yes please https://pyviz.org/tools.html#all-tools

e.g. when you hover over all-tools it gives the options of "permalink to this headline". I don't see that with core and the others

**Comment by jbednar** [comment]
Ah.  I think the top-level heading is handled in Markdown, while we're creating the raw HTML for the actual tools listing from a template.  The line involved is [`<h3 id="{{ section.name.lower().replace(' ', '-') }}">{{ section.name }}</h3>`](https://github.com/pyviz/pyviz.org/blob/master/tools/template.html#L3), and it looks like the HTML code for that first heading ends up as `<a class="headerlink" href="#all-tools" title="Permalink to this headline">¶</a>`. So we could try changing that line to `<h3 id="{{ section.name.lower().replace(' ', '-') }}">{{ section.name }}<a class="headerlink" href="#{{ section.name.lower().replace(' ', '-') }}" title="Permalink to {{ section.name }}">¶</a></h3>`. Might work?

**Comment by jbednar** [comment]
Seems to have worked!

**Comment by raybellwaves** [comment]
thanks!
