### ISSUE TITLE
 Pypi "invalid" statements

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyviz/pyviz.org#107]
In a lot of places the pypi numbers are "invalid".

https://pyviz.org/tools.html

![image](https://user-images.githubusercontent.com/42288570/118369070-4cef9b00-b5a3-11eb-8e2a-4244c693f7ea.png)

**Comment by maximlt** [comment]
Fixed by https://github.com/pyviz/pyviz.org/pull/109
