### ISSUE TITLE
Panel conda badge not upto date: shows Panel version 0.12.1

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyviz/pyviz.org#117]
![image](https://user-images.githubusercontent.com/42288570/146508512-acbcc05f-3a84-4494-b9c1-497b59fd6af1.png)

https://pyviz.org/tools.html

**Comment by jbednar** [comment]
I believe that is accurate; the version of Panel currently on anaconda defaults is 0.12.1:

![image](https://user-images.githubusercontent.com/1695496/146588860-37549eeb-ca2f-46bf-8609-2353f2c3ff31.png)

There are newer conda packages on the `pyviz` and `conda-forge` channels. Here we could add `conda_channel: conda-forge` or `pyviz` to the panel section of tools.yml, as those are more often up to date, but I'd guess most people install from defaults.
