### ISSUE TITLE
Add Gradio and PyWebIO to dashboards section

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyviz/pyviz.org#118]
https://twitter.com/andfanilo/status/1471750918525919237?s=20

![image](https://user-images.githubusercontent.com/42288570/146510022-e16faed7-2891-453a-9d79-3c3d274dca9e.png)

**Comment by jbednar** [comment]
Please do add those, thanks!

**Comment by jbednar** [comment]
Added to tools.yml
