### ISSUE TITLE
drill down or deep hierarchy table which has multiple level

### ISSUE THREAD

**Issue by basicx-shivani** [pyviz/pyviz.org#123]
not able to create drill down table by panel or hierarchy table which has parent child recursive table.
i used pn.widgets,DataFrame(df, hierarchical==True) but it only giving me one level go down not in tree form.

**Comment by jbednar** [comment]
That sounds like a feature request for [Panel](https://github.com/holoviz/panel/issues). https://panel.holoviz.org/reference/widgets/Tabulator.html may offer something like that; not sure.
