### ISSUE TITLE
Biggles seems dormant

### ISSUE THREAD

**Issue by Make42** [pyviz/pyviz.org#133]
Biggles has no update on Github for 2 years. Seems it is dormant and should be moved to "Dormant projects" in https://pyviz.org/tools.html.

Further evidence: https://github.com/biggles-plot/biggles/issues/144

**Comment by jbednar** [comment]
Sounds like it! Happy to accept a PR to that effect.

**Comment by jbednar** [comment]
Now re-categorized; thanks for the issue!
