### ISSUE TITLE
pyviz installation error

### ISSUE THREAD

**Issue by chanansh** [pyviz/pyviz.org#135]
I am trying to install the package on a Python 3.8.10
I get the following error:

```(.venv) root@hanan-cpu-only-0:/home/jovyan/switch-power-optimization/data/msft_phx80_6_28# poetry add pyviz
Using version ^0.10.3 for pyviz

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  Because no versions of pyviz match >0.10.3,<0.11.0
   and pyviz (0.10.3) depends on matplotlib (3.0.3), pyviz (>=0.10.3,<0.11.0) requires matplotlib (3.0.3).
  So, because switch-power-optimization depends on both matplotlib (^3.5.3) and pyviz (^0.10.3), version solving failed.

  at /usr/local/lib/python3.8/dist-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
(.venv) root@hanan-cpu-only-0:/home/jovyan/switch-power-optimization/data/msft_phx80_6_28# ```

with pip I get

```
pip install pyviz
Collecting pyviz
  Using cached pyviz-0.10.3-py2.py3-none-any.whl (16.4 MB)
Collecting rise
  Using cached rise-5.7.1-py2.py3-none-any.whl (4.3 MB)
Collecting netcdf4
  Using cached netCDF4-1.6.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.2 MB)
Collecting hvplot>=0.4.0
  Using cached hvplot-0.8.1-py2.py3-none-any.whl (3.2 MB)
Requirement already satisfied: notebook>=5.5 in /home/jovyan/switch-power-optimization/.venv/lib/python3.8/site-packages (from pyviz) (6.4.12)
Collecting fastparquet>=0.2.1
  Using cached fastparquet-0.8.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Collecting ipython<=7.1.1,>=5.4.0
  Using cached ipython-7.1.1-py3-none-any.whl (764 kB)
Collecting panel>=0.6.0
  Using cached panel-0.13.1-py2.py3-none-any.whl (15.7 MB)
Collecting bokeh>=1.2.0
  Using cached bokeh-2.4.3-py3-none-any.whl (18.5 MB)
Collecting xarray<0.12,>=0.11.0
  Using cached xarray-0.11.3-py2.py3-none-any.whl (504 kB)
Requirement already satisfied: numpy>=1.16.4 in /home/jovyan/switch-power-optimization/.venv/lib/python3.8/site-packages (from pyviz) (1.23.2)
Collecting selenium
  Using cached selenium-4.4.3-py3-none-any.whl (985 kB)
Collecting holoviews>=1.12.3
  Using cached holoviews-1.15.0-py2.py3-none-any.whl (4.3 MB)
Collecting streamz
  Using cached streamz-0.6.4-py2.py3-none-any.whl (76 kB)
Requirement already satisfied: ipywidgets in /home/jovyan/switch-power-optimization/.venv/lib/python3.8/site-packages (from pyviz) (8.0.1)
Requirement already satisfied: dask[complete]>=0.18.2 in /home/jovyan/switch-power-optimization/.venv/lib/python3.8/site-packages (from pyviz) (2022.8.1)
Collecting pandas<0.25.0,>=0.23.4
  Using cached pandas-0.24.2.tar.gz (11.8 MB)
  Preparing metadata (setup.py) ... done
Collecting pyct[cmd]>=0.4.6
  Using cached pyct-0.4.8-py2.py3-none-any.whl (15 kB)
Collecting matplotlib==3.0.3
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-go5lss7q/matplotlib_1a199b31dccd43148bdafcc7f122c4bb/setup.py", line 225, in <module>
          msg = pkg.install_help_msg()
        File "/tmp/pip-install-go5lss7q/matplotlib_1a199b31dccd43148bdafcc7f122c4bb/setupext.py", line 650, in install_help_msg
          release = platform.linux_distribution()[0].lower()
      AttributeError: module 'platform' has no attribute 'linux_distribution'
      ============================================================================
      Edit setup.cfg to change the build options
      
      BUILDING MATPLOTLIB
                  matplotlib: yes [3.0.3]
                      python: yes [3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC
                              9.4.0]]
                    platform: yes [linux]
      
      REQUIRED DEPENDENCIES AND EXTENSIONS
                       numpy: yes [version 1.23.2]
            install_requires: yes [handled by setuptools]
                      libagg: yes [pkg-config information for 'libagg' could not
                              be found. Using local copy.]
                    freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                              could not be found.  You may need to install the
                              development package.]
                         png: no  [pkg-config information for 'libpng' could not
                              be found.]
                       qhull: yes [pkg-config information for 'libqhull' could not
                              be found. Using local copy.]
      
      OPTIONAL SUBPACKAGES
                 sample_data: yes [installing]
                    toolkits: yes [installing]
                       tests: no  [skipping due to configuration]
              toolkits_tests: no  [skipping due to configuration]
      
      OPTIONAL BACKEND EXTENSIONS
                         agg: yes [installing]
                       tkagg: yes [installing; run-time loading from Python Tcl /
                              Tk]
                      macosx: no  [Mac OS-X only]
                   windowing: no  [Microsoft Windows only]
      
      OPTIONAL PACKAGE DATA
                        dlls: no  [skipping due to configuration]
      
      ============================================================================
                              * The following required packages can not be built:
                              * freetype, png
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(.venv) root@hanan-cpu-only-0:/home/jovyan/switch-power-optimization/data/msft_phx80_6_28# pip install pyviz > error.log
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6zcq2qve/matplotlib_3648b71da76048c58960c4b61bb772d0/setup.py", line 225, in <module>
          msg = pkg.install_help_msg()
        File "/tmp/pip-install-6zcq2qve/matplotlib_3648b71da76048c58960c4b61bb772d0/setupext.py", line 650, in install_help_msg
          release = platform.linux_distribution()[0].lower()
      AttributeError: module 'platform' has no attribute 'linux_distribution'
      ============================================================================
      Edit setup.cfg to change the build options
      
      BUILDING MATPLOTLIB
                  matplotlib: yes [3.0.3]
                      python: yes [3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC
                              9.4.0]]
                    platform: yes [linux]
      
      REQUIRED DEPENDENCIES AND EXTENSIONS
                       numpy: yes [version 1.23.2]
            install_requires: yes [handled by setuptools]
                      libagg: yes [pkg-config information for 'libagg' could not
                              be found. Using local copy.]
                    freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                              could not be found.  You may need to install the
                              development package.]
                         png: no  [pkg-config information for 'libpng' could not
                              be found.]
                       qhull: yes [pkg-config information for 'libqhull' could not
                              be found. Using local copy.]
      
      OPTIONAL SUBPACKAGES
                 sample_data: yes [installing]
                    toolkits: yes [installing]
                       tests: no  [skipping due to configuration]
              toolkits_tests: no  [skipping due to configuration]
      
      OPTIONAL BACKEND EXTENSIONS
                         agg: yes [installing]
                       tkagg: yes [installing; run-time loading from Python Tcl /
                              Tk]
                      macosx: no  [Mac OS-X only]
                   windowing: no  [Microsoft Windows only]
      
      OPTIONAL PACKAGE DATA
                        dlls: no  [skipping due to configuration]
      
      ============================================================================
                              * The following required packages can not be built:
                              * freetype, png
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by maximlt** [comment]
Pyviz.org is a website that describes the Visualization landscape to Python users. I guess at some point the `pyviz` package was a meta-package used to install the HoloViz tools, but it's definitely not maintained anymore and I'm pretty sure there's no place where this is documented. Please install directly the libraries you need, e.g. `pip install hvplot plotly ...`
