### ISSUE TITLE
Dormant projects

### ISSUE THREAD

**Issue by jbednar** [pyviz/pyviz.org#14]
As of #11, the tools listing includes dormant projects, along with a link to the indication that they are dormant.  For the ones currently included, the link goes either to a public statement that the package is no longer being maintained, or to a listing of repository activity that shows essentially no development over the preceding two years.

Hopefully this list will help people make sense of the many available projects, steering people to an appropriate alternative.  In some cases, there is a public statement by the library author of what library to consider instead, e.g.:

- visvis was [superseded by vispy](https://github.com/almarklein/visvis#status)
- galry was [superseded by vispy](https://github.com/rossant/galry/blob/master/README.md)
- lightning [suggests using plotly instead](https://gitter.im/lightning-viz/lightning)
- basemap [suggests using cartopy](https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement)

In other cases, there seems to be a very reasonable alternative to suggest:

- ggpy/ggplot was [rewritten to become plotnine](https://plotnine.readthedocs.io/en/stable/about-plotnine.html)
- vincent was a Vega wrapper, like the currently maintained [altair](https://github.com/python-visualization/folium/issues/480).

We could include this information in the listing ("Suggested alternative"?), but it might get a bit tricky; e.g. lots of libraries could claim to be good alternatives to Lightning. For now we've omitted that information, but discussion could happen here if someone wants to include it.

**Comment by tacaswell** [comment]
attn @weathergod regarding basemap.

**Comment by jbednar** [comment]
Quoting from [matplotlib.org/basemap/users/intro.html](https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement) : 
![image](https://user-images.githubusercontent.com/1695496/61103565-20fbaf80-a438-11e9-83a0-eee3b63403ac.png)

**Comment by WeatherGod** [comment]
I agree with the assertion that basemap is to be superseded by cartopy. Dormant might not be quite the right word, but I won't quibble over the semantics this close to 2020.
