### ISSUE TITLE
How to share global dataframe object across users?

### ISSUE THREAD

**Issue by Nithanaroy** [pyviz/pyviz.org#65]
I recently started exploring pyviz suite of tools and absolutely love them! Some amazing algorithms that work together so seamlessly and efficiently.

Is it possible to share `df` global variable (w.r.t `OSMExplorer` class) across users [in this tutorial](https://youtu.be/k27MJJLJNT4?t=593)?

The motivation is to reduce initial load times for users. Currently my app takes more than a minute the first time I load a page in a browser after `bokeh serve`. If I open a new incognito window (to mimic another user), it again takes a minute. I'm assuming this happens because a new `df` is created for every user session. Just like Pandas creates views on every transformation, mimicking a copy, can I do something in `OSMExplorer.do_view` as well? Unable to share the dashboard to others as it too long to load.

Thanks in advance for help :)

**Comment by jbednar** [comment]
Can you please re-open this issue on https://github.com/holoviz/panel/issues ? This repository is specifically for the pyviz.org website, not any particular tool.  In any case, the answer right now is to store global state in `pn.state.cache`, which will be available to all sessions...

**Comment by Nithanaroy** [comment]
Oh sorry. I checked the issues there and saw a few already on this topic. Was able to get it working with `pn.state.cache` for now.
