### ISSUE TITLE
not able to get pyviz through conda install command on windows

### ISSUE THREAD

**Issue by nickhalden** [pyviz/pyviz.org#67]
not able to get pyviz through conda install command on windows. I was wondering it it's because of the red build you have with travis CI?

**Comment by jbednar** [comment]
I'm not sure what you mean; there's not currently any "pyviz" package to install; PyViz is an overview and guide to other packages.  Are you looking for the "holoviz" package, from http://holoviz.org? 

The red build is about the latest build to update the PyViz.org website, which should be unrelated.
