### ISSUE TITLE
add an explicit command to create a Conda kernel for Jupyter

### ISSUE THREAD

**Issue by polinas123** [pyviz/pyviz.org#82]
when setting up using [these instructions on the holoviz tutorial webpage](https://holoviz.org/tutorial/Setup.html) there is a missing step required to get the first cell running. Conda stopped automatically setting environments up as jupyter kernels. So after activating the env, you need to manually add the kernel, using something like: `python -m ipykernel install --user --name holoviz-tutorial --display-name "Python3 (holoviz-tutorial)"`. Then after running Jupyter you can select the right kernel. Otherwise Jupiter will not show that kernel and you will get import errors for already installed packages. I tried this on Mac and Jupyter lab.

**Comment by philippjfr** [comment]
>Conda stopped automatically setting environments up as jupyter kernels

That would be news to me, if you look inside the ipykernel conda package you will find this:

<img width="794" alt="Screen Shot 2020-08-31 at 9 14 53 PM" src="https://user-images.githubusercontent.com/1550771/91757743-21708000-ebcf-11ea-8f79-ba2f6db9fec2.png">

which is what's needed to install the kernel.

**Comment by jbednar** [comment]
Maybe you skipped the activation step?  In any case, if there is an issue, please post it at https://github.com/holoviz/holoviz ; this repo is about a different set of tools.

**Comment by jbednar** [comment]
Oh, and if you're running JupyterLab, remember to install the JupyterLab extension! (Step 4, option B at http://holoviz.org/installation.html .)
