### ISSUE TITLE
Add Streamlit conda package to all tools overview

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyviz/pyviz.org#95]
Streamlit now has a conda package https://anaconda.org/conda-forge/streamlit

![image](https://user-images.githubusercontent.com/42288570/101236199-7987b880-36cf-11eb-9439-2ba3771be3e5.png)

![image](https://user-images.githubusercontent.com/42288570/101236209-8c9a8880-36cf-11eb-80ad-db2e47d2cbf3.png)

**Comment by jbednar** [comment]
Yes, I saw that as soon as the badges came up (@jlstevens fixed them last night), and have a fix for that and some other packages that are now on conda-forge already on my hard drive, but my wife told me that it was Friday night and I needed to put the damn computer away. :-)

**Comment by jbednar** [comment]
Fixed in https://github.com/pyviz/pyviz.org/pull/97.
